name = "GraphLaplacians"
uuid = "a1251efa-393a-423f-9d7b-faaecba535dc"
authors = ["Yueh-Hua Tu"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
